#pragma once
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
//#include <GL/glut.h>
#include <iostream>
#include <algorithm>
#include <time.h>
#include <chrono>
#include <string>
#include <fstream>
#include <sstream>