#version 460 core
layout(local_size_x = 1, local_size_y = 1,local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D TrailMap;
layout(std460, binding = 1) buffer Agent {
    vec2 Pos;
    vec2 Dir;
};Agents[]

uniform int SpawnMode;
uniform int width;
uniform int height;

float rand(vec2 co);

void main()
{
    vec2 center = vec2(width/2,height/2);
    if(SpawnMode == 0)//Spawn agents in the center of the map with a random angle
    {
        Agents[gl_GlobalInvocationID.x].Pos = center;
        Agents[gl_GlobalInvocationID.x].Dir.x = rand() % 360;
    }

}

float rand(vec2 co)
{
    return fract(sin(dot(co, vec2(12.9898, 78.233))) * 43758.5453);
}
